# [START app_yaml]
runtime: nodejs  
instance_class: F4_1G
env_variables:
  DB_USER: postgres
  DB_NAME: postgres
  DB_PASSWORD: gotham
  PORJECT_ID: myproject1-246117:us-central1:assessment
  CLOUD_SQL_CONNECTION_NAME: myproject1-246117:us-central1:assessment
  SENDGRIDAPIKEY: AIzaSyAXYFVIyWs12ZcmkOTC5KZjYqmledGQKmc
beta_settings:
  cloud_sql_instances: myproject1-246117:us-central1:assessment
# [END app_yaml]